#! /usr/bin/env bash
# Install proxmox automatically
# Intended for Debian 10 (buster)
# and proxmox 6.1


# Log all hidden actions in this log

LOGFILE=proxmox.log

# Set DRYRUN=1
# to test the script without actually installing anything

DRYRUN=1

if [ $DRYRUN -eq 1 ]; then
  APTOPTIONS="--dry-run"
else
  APTOPTIONS=""
fi

# Check if requested package is installed
# and install otherwise. 

function check_install {
  echo -n "Checking for $1..."
  dpkg -s $1 >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "OK"
    return 0
  else
    echo -n "installing..."
    apt-get install -y $APTOPTIONS $1 >>$LOGFILE 2>&1
    if [ $? -eq 0 ]; then
      echo "installed ok"
      return 0
    else
      echo "failed."
      exit 1
    fi
  fi
}


clear
echo "Proxmox Installation Script"
echo "==========================="
echo "(C) 2020 Manolis Kiagias"
echo 
echo "Before running this script make sure:"
echo 
echo "1. You have setup your NICs and assigned IPs"
echo "2. You have a hosts file that resolves hostnames to real IPs (not loopback)"
echo "3. Your hosts file can resolve the other cluster members"
echo "4. You have passwordless SSH for root and keys in place"
echo
echo "Press CTRL+C to exit now or" 
read -p "press enter to continue"
clear
echo "Checking and installing some prerequisites..."

check_install "aptitude"
check_install "wget"
check_install "ntp"

echo -n "Adding proxmox sources..."

if [ -z "$APTOPTIONS" ]; then
  echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list 
fi

if [ $? -eq 0 ]; then
  echo "OK"
else
  echo "Failed!"
  exit 1
fi 

echo -n "Adding proxmox keys..."

if [ -z "$APTOPTIONS" ]; then
  wget http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg >>proxmox.log 2>&1
fi

if [ $? -eq 0 ]; then
  echo "OK"
else
  echo "Failed!"
  exit 1
fi

echo -n "Updating the debian system..."

apt-get $APTOPTIONS -y update >>proxmox.log 2>&1
apt-get $APTOPTIONS -y upgrade >>proxmox.log 2>&1
apt-get $APTOPTIONS -y dist-upgrade >>proxmox.log 2>&1

echo "Done."

check_install "ifupdown2"

echo -n "Uninstalling incompatible software..."

if [ -z "$APTOPTIONS" ]; then
  aptitude -q -y purge firmware-bnx2x firmware-realtek firmware-linux firmware-linux-free firmware-linux-nonfree >>proxmox.log 2>&1
fi

echo "OK"

echo 
echo "Ready to install proxmox-ve "
echo "============================"
echo "If installation freezes during pve-manager, reboot the system"
echo "and run dpkg --configure -a"
read -p "Press Enter to continue"

clear
echo "Installing proxmox-ve..."
if [ -z "$APTOPTIONS" ]; then
  apt-get install proxmox-ve
fi

# Remove the pve-enterprise.list, this is only for people with
# subscriptions :D

rm /etc/apt/sources.list.d/pve-enterprise.list >>proxmox.log 2>&1

echo "Installation complete! Please reboot to activate."
